/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustlinesRouteImport } from './routes/trustlines'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as NewChatRouteImport } from './routes/new-chat'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TxHashRouteImport } from './routes/tx.$hash'
import { Route as ChatIdRouteImport } from './routes/chat.$id'

const TrustlinesRoute = TrustlinesRouteImport.update({
  id: '/trustlines',
  path: '/trustlines',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const NewChatRoute = NewChatRouteImport.update({
  id: '/new-chat',
  path: '/new-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TxHashRoute = TxHashRouteImport.update({
  id: '/tx/$hash',
  path: '/tx/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/new-chat': typeof NewChatRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/trustlines': typeof TrustlinesRoute
  '/chat/$id': typeof ChatIdRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/new-chat': typeof NewChatRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/trustlines': typeof TrustlinesRoute
  '/chat/$id': typeof ChatIdRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/new-chat': typeof NewChatRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/trustlines': typeof TrustlinesRoute
  '/chat/$id': typeof ChatIdRoute
  '/tx/$hash': typeof TxHashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contacts'
    | '/new-chat'
    | '/receive'
    | '/send'
    | '/trustlines'
    | '/chat/$id'
    | '/tx/$hash'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contacts'
    | '/new-chat'
    | '/receive'
    | '/send'
    | '/trustlines'
    | '/chat/$id'
    | '/tx/$hash'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contacts'
    | '/new-chat'
    | '/receive'
    | '/send'
    | '/trustlines'
    | '/chat/$id'
    | '/tx/$hash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactsRoute: typeof ContactsRoute
  NewChatRoute: typeof NewChatRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  TrustlinesRoute: typeof TrustlinesRoute
  ChatIdRoute: typeof ChatIdRoute
  TxHashRoute: typeof TxHashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trustlines': {
      id: '/trustlines'
      path: '/trustlines'
      fullPath: '/trustlines'
      preLoaderRoute: typeof TrustlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-chat': {
      id: '/new-chat'
      path: '/new-chat'
      fullPath: '/new-chat'
      preLoaderRoute: typeof NewChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tx/$hash': {
      id: '/tx/$hash'
      path: '/tx/$hash'
      fullPath: '/tx/$hash'
      preLoaderRoute: typeof TxHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactsRoute: ContactsRoute,
  NewChatRoute: NewChatRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  TrustlinesRoute: TrustlinesRoute,
  ChatIdRoute: ChatIdRoute,
  TxHashRoute: TxHashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
